apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
  namespace: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: stockexchange
spec:
  parentRefs:
    - name: stockexchange
      namespace: nginx-gateway
  hostnames:
    - web.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web
          port: 8080
